name: 'dynamics_365_crm_integration_tests'
version: '0.1.0'
profile: 'integration_tests'
config-version: 2

vars:
  # Generate docs using "dbt docs generate --empty-catalog"
  dynamics_365_crm_schema: zz_d365 #dynamics_365_crm_integration_tests
  dynamics_365_crm:
    dynamics_365_crm_account_identifier: "account_data"
    dynamics_365_crm_appointment_identifier: "appointment_data"
    dynamics_365_crm_contact_identifier: "contact_data"
    dynamics_365_crm_incident_identifier: "incident_data"
    dynamics_365_crm_opportunity_identifier: "opportunity_data"
    dynamics_365_crm_phonecall_identifier: "phonecall_data"
    dynamics_365_crm_stringmap_identifier: "stringmap_data"
    dynamics_365_crm_systemuser_identifier: "systemuser_data"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
